# Generated by Django 3.2.9 on 2021-11-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211128_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='size',
        ),
    ]
