# Generated by Django 3.2.9 on 2021-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211128_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tradeSize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='exitDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lastUpdatedOn',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='totalQuantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
