# Generated by Django 3.2.8 on 2021-10-09 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(default=datetime.datetime(2021, 10, 9, 11, 6, 28, 764648, tzinfo=utc))),
                ('exchange_name', models.CharField(max_length=255)),
                ('token_name', models.CharField(max_length=255)),
                ('buy_rate', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('sale_rate', models.FloatField(default=0.0)),
                ('date_of_sale', models.DateTimeField(default=datetime.datetime(2021, 10, 9, 11, 6, 28, 764821, tzinfo=utc))),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(default=datetime.datetime(2021, 10, 9, 11, 6, 28, 764874, tzinfo=utc))),
            ],
        ),
    ]
